// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTj_n_0o0qXVacPWQ9JM70U-lIvfUZY4w',
    appId: '1:488756701457:web:fc74aa2cd75d117fdd84b0',
    messagingSenderId: '488756701457',
    projectId: 'auth-app-98bb8',
    authDomain: 'auth-app-98bb8.firebaseapp.com',
    databaseURL: 'https://auth-app-98bb8-default-rtdb.firebaseio.com',
    storageBucket: 'auth-app-98bb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQeKIMzU4jJJYPOy_PMM4ZzlIRJoPU6w',
    appId: '1:488756701457:android:7e784d09da0973d0dd84b0',
    messagingSenderId: '488756701457',
    projectId: 'auth-app-98bb8',
    databaseURL: 'https://auth-app-98bb8-default-rtdb.firebaseio.com',
    storageBucket: 'auth-app-98bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOt-hCLoQe2DPiUeHdo0vqrMMqrDC6Mpk',
    appId: '1:488756701457:ios:e82a71630f41a70fdd84b0',
    messagingSenderId: '488756701457',
    projectId: 'auth-app-98bb8',
    databaseURL: 'https://auth-app-98bb8-default-rtdb.firebaseio.com',
    storageBucket: 'auth-app-98bb8.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

}